site_name: COMP2801
site_url: https://gdoyle87.github.io/COMP2801/
nav:
  - Home: index.md
  - Week 1 - Formatted Output in C: wk_one.md
  - Week 2 - scanf and Recursion: wk_two.md
  - Week 3 - Structures and typedef: wk_three.md
  - Week 4 - Unions, Bit manipulations: wk_four.md
  - Week 5 - Linked Lists and Trees: wk_five.md
  - Week 6 - Stacks and Queues: wk_six.md
  - Midterm Study Notes: midterm.md
  - Week 7 - Big O Notation, Selection Sort, Insertion Sort: wk_seven.md
  - Week 8 - Files: wk_eight.md
  - Week 9 - CLI, calloc and realloc, and other random stuff: wk_nine.md
  - COMP 2701: https://gdoyle87.github.io/COMP2701
  - Other Notes: https://gdoyle87.github.io/

theme:
  name: material
  features:
    - toc.integrate # move page TOC into the left nav
    - navigation.expand # expand sections by default (feels like RTD)
    - navigation.sections
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.superfences
  - pymdownx.details

#extra_javascript:
#  - https://cdn.jsdelivr.net/npm/asciinema-player@2.6.1/resources/public/js/asciinema-player.js
#  - js/ll_stepper.js
#
#extra_css:
#  - https://cdn.jsdelivr.net/npm/asciinema-player@2.6.1/resources/public/css/asciinema-player.css
#  - styles/print.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.12.1/dist/bundle/asciinema-player.min.js
  - js/asciinema-init.js
  - js/ll_stepper.js

extra_css:
  - https://cdn.jsdelivr.net/npm/asciinema-player@3.12.1/dist/bundle/asciinema-player.css
  - styles/print.css
  - styles/asciinema_extra.css
